// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef _32X_TILESET_INCLUDE_H
#define _32X_TILESET_INCLUDE_H

#include <stdint.h>

extern const uint8_t _32x_tileset[19328]; // 604 tiles

#endif // _32X_TILESET_INCLUDE_H
