// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef _32X_PALETTE_INCLUDE_H
#define _32X_PALETTE_INCLUDE_H

#include <stdint.h>

extern const uint16_t _32x_palette[16];

#endif // _32X_PALETTE_INCLUDE_H
