// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef GENESIS_PALETTE_INCLUDE_H
#define GENESIS_PALETTE_INCLUDE_H

#include <stdint.h>

extern const uint16_t genesis_palette[16];

#endif // GENESIS_PALETTE_INCLUDE_H
