// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef GENESIS_PALETTE_INCLUDE_H
#define GENESIS_PALETTE_INCLUDE_H

extern const unsigned short genesis_palette[16];

#endif // GENESIS_PALETTE_INCLUDE_H
