// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef GENESIS_TILEMAP_INCLUDE_H
#define GENESIS_TILEMAP_INCLUDE_H

#include <stdint.h>

extern const uint16_t genesis_tilemap[1120];

#endif // GENESIS_TILEMAP_INCLUDE_H
