// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef GENESIS_TILEMAP_INCLUDE_H
#define GENESIS_TILEMAP_INCLUDE_H

extern const unsigned short genesis_tilemap[1120];

#endif // GENESIS_TILEMAP_INCLUDE_H
