// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef GENESIS_TILESET_INCLUDE_H
#define GENESIS_TILESET_INCLUDE_H

#include <stdint.h>

extern const uint8_t genesis_tileset[13408]; // 419 tiles

#endif // GENESIS_TILESET_INCLUDE_H
