// File generated by bmp2bg. https://github.com/pw32x/bmp2bg
#ifndef SPHERE32X32_4BPP_PALETTE_INCLUDE_H
#define SPHERE32X32_4BPP_PALETTE_INCLUDE_H

#include <stdint.h>

extern const uint16_t sphere32x32_4bpp_palette[16];

#endif // SPHERE32X32_4BPP_PALETTE_INCLUDE_H
